

server:
  port: ${port:8086}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

######################################
#########  DB PROPERTIES #############
######################################
spring:
  datasource:
    url: ${datasourceUrl:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${dbusername:admin}
    password: ${password:test123}
    driver-class-name: ${diverclassname:org.postgresql.Driver}


routing:
  header: ${ROUTING_HEADER:testHeader}
  mappings:
    pacs.008.001.09: ${ROUTING_CHANNEL1:pacs008}
    camt.059.001.06: ${ROUTING_CHANNEL2:camt59}
    camt.054.001.08: ${ROUTING_CHANNEL3:camt_52_54}
    camt.052.001.08: ${ROUTING_CHANNEL4:camt_52_54}
    admi: ${ROUTING_CHANNEL5:channelA}

message:
  xpath:
    mappings:
      pacs.008.001.09: ${MAPPING_PACS008://*[local-name()="CdtTrfTxInf"]}
      camt.059.001.04: ${MAPPING_CAMT59://*[local-name()="OrgnlNtfctnRef"]}
      # Add more message types and their XPaths as needed

topic:
  fctopic: ${FCTOPIC:FCTOPIC}
  ephtopic: ${EPHTOPIC:EPHTOPIC}
  sfmstopic: ${SFMSTOPIC:SFMSTOPIC}

