server:
  port: ${port:8088}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

spring:
  application:
    name: nil-router

  cloud:
    stream:
      function:
        definition: processStream

      bindings:
        processStream-in-0:
          destination: TOPIC
          contentType: text/plain
          consumer:
            useNativeDecoding: true

        processStream-out-0:
          destination: FCTOPIC
          contentType: text/plain
          producer:
            useNativeEncoding: true

        processStream-out-1:
          destination: EPHTOPIC
          contentType: text/plain
          producer:
            useNativeEncoding: true

        processStream-out-2:
          destination: SFMS
          contentType: text/plain
          producer:
            useNativeEncoding: true

        processStream-out-3:
          destination: MSGEVENTTRACKERTOPIC
          contentType: text/plain
          producer:
            useNativeEncoding: true

      kafka:
        streams:
          binder:
            brokers: 34.28.251.45:9092
            functions:
              processStream:
                applicationId: nil-router
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000




####################################################



  ######################################
  #########  DB PROPERTIES #############
  ######################################

  datasource:
    url: ${datasourceUrl:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${dbusername:admin}
    password: ${password:test123}
    driver-class-name: ${diverclassname:org.postgresql.Driver}


routing:
  header: testHeader
  mappings:
    pacs.008.001.09: pacs008
    camt.059.001.06: camt59
    camt.054.001.08: camt_52_54
    camt.052.001.08: camt_52_54
    admi.004.001.01: admi004
    admi.004.001.02: admi004
    pacs.002.001.11: pacs002
    pacs.004.001.10: pacs004
    #camt.059.001.06: camt59
    admi: channelA

message:
  xpath:
    mappings:
      pacs.008.001.09: "//*[local-name()='CdtTrfTxInf']"
      camt.059.001.06: "//*[local-name()='OrgnlNtfctnRef']"
      #camt.054.001.08: "//*[local-name()='TxDtls']"
      #camt.052.001.08: "//*[local-name()='TxDtls']"
      pacs.004.001.10: "//*[local-name()='TxInf']"
      # Add more message types and their XPaths as needed
    #pacs.008.001.09: pacs008


topic:
  fctopic: FCTOPIC
  ephtopic: EPHTOPIC
  sfmstopic: SFMSTOPIC
  msgeventtrackertopic: MSGEVENTTRACKERTOPIC

cug_flag: ${CUG_FLAG:true}

